### ISSUE TITLE
error decoding event ?

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/knative-lambda-runtime#1]
deployment worked but got this during the `--wait`:

```
$ tm deploy service python-test -f https://github.com/serverless/examples --build-template aws-python37-runtime --build-argument DIRECTORY=aws-python-simple-http-endpoint --build-argument HANDLER=handler.endpoint --wait
Creating python-test function
Deployment started. Run "tm -n sebgoa describe service python-test" to see the details
Waiting for ready state............ERROR: logging before flag.Parse: E1218 22:24:05.266184    8707 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 5; INTERNAL_ERROR
............ERROR: logging before flag.Parse: E1218 22:25:05.359689    8707 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 7; INTERNAL_ERROR
.......
```

**Comment by tzununbekov** [comment]
looks like low-level "watch" interface communication issue, like connection timeout or something similar. Found several bug reports with same symptoms, but couldn't reproduce it.
Will keep in mind if it appear again or we find a reproducible case.

**Comment by tzununbekov** [comment]
As a part of `kdemo` project deployment fixes it was confirmed that such messages are not critical and not affecting deployment process. Also, few more condition checks and watch interface restart operations were added to ensure deployment reliability
