### ISSUE TITLE
Bug: function deployment outputs error

### ISSUE THREAD

**Issue by anatoliyfedorenko** [triggermesh/knative-lambda-runtime#20]
Tried to deploy functions with NodeJS and Go, after a lot of waiting, it outputs the following lines:
`ERROR: logging before flag.Parse: E0115 15:54:14.201737   27783 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 123; INTERNAL_ERROR`

Then I quit, but after all found out that the function indeed works, just need to wait some more time. Need to understand where it comes from and how to avoid that error.

**Comment by tzununbekov** [comment]
Duplicates #1

**Comment by tzununbekov** [comment]
@anatoliyfedorenko what version of `tm` are you using?

**Comment by sebgoa** [comment]
I think it is an issue with pushing to the registry

**Comment by sebgoa** [comment]
LEt's close as duplicate of #1
