### ISSUE TITLE
show example with a different registry than the default in `tm`

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/knative-lambda-runtime#21]
the README shows `tm` command but it assumes internal registry.

We need to document how to deploy the function with a different registry.

**Comment by solsson** [comment]
I'll wait for the `tm` change with `set registry-auth`, and https://github.com/triggermesh/tm/issues/69

**Comment by solsson** [comment]
Was closed after I merged #24, because it's an improvement from having no registry documentation at all, but I'll reopen because we still don't document an example with a different registry.
