### ISSUE TITLE
Check the response format 

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/knative-lambda-runtime#23]
It seems we are returning the entire reponse including the statusCode.

Following a sample demo in:
https://github.com/sebgoa/klr-demo

If we deploy the function with sls we get:

```
$ curl https://10sjc1yh84.execute-api.us-east-1.amazonaws.com/dev/ping
{"message": "Hello, the current time is 09:03:58.049756"}
```

Just get the body

but with KLR:

```
curl http://python-test.sebgoa.k.triggermesh.io
{"statusCode": 200, "body": "{\"message\": \"Hello, the current time is 09:16:44.925908\"}"}
```

**Comment by tzununbekov** [comment]
looks like this response format (`{"statusCode":int, "body":"string",etc}`) is supposed to be handled in AWS API Gateway service which may work as AWS Lambda proxy. I can be wrong with a wording, full description is [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-integration-settings-integration-response.html)

So, on the one hand, I'd not want to add more AWS-like integrations to our custom runtime to keep it simple and pass function responses "as is". But on the other hand, I see many lambda functions with this response format, so I think I can make our AWS runtime check if response comes in API Gateway format, parse it and pass formed HTTP response to user.

**Comment by sebgoa** [comment]
I wouldn't modify anything. Indeed this response format is due to AWS APi gateway, there are other examples (functions not exposed via API gateway) that don't have such a response because they are tied to other services.

So we should not change things. Instead find better examples:

see Alexa for example which has yet a different response format:
https://github.com/serverless/examples/blob/master/aws-python-alexa-skill/handler.py

**Comment by tzununbekov** [comment]
I wish I could notice last comment before my [commit](https://github.com/triggermesh/aws-custom-runtime/commit/5740205ceb07733eb3b177f2ff11b78cf8437884). However, I reverted it but we'll have it in commits history, just in case :)

**Comment by tzununbekov** [comment]
API gateway format conversion can be enabled by setting `EVENT` env variable value to `API_GATEWAY`. Implemented [here](https://github.com/triggermesh/aws-custom-runtime/blob/a930c6e8a807748a54fd96ba229878887ce13eff/main.go#L211-L224)
