### ISSUE TITLE
Go: import and share private vendor packages

### ISSUE THREAD

**Issue by tzununbekov** [triggermesh/knative-lambda-runtime#27]
Need to figure out how to properly import dependencies from private git repositories (for go runtime). Furthermore, we must have ability to share vendored packages between functions of same project (described in one yaml manifest)

**Comment by sebgoa** [comment]
Sharing of vendored packages is really what AWS Lambda layers are about. I think it is a very good idea to explore but will be tied to the registry used.

https://github.com/awslabs/aws-lambda-container-image-converter

For now, I would stick with a way to handle dependencies. (the sharing is an optimization)

**Comment by tzununbekov** [comment]
Added `tm set git-auth` command to create k8s secret with SSH private key that will be used for `git clone`, `dep ensure`, etc operations. Added readme note about it.
Also, for now `tm set git-auth` works with only one ssh key that will be used for all private repository, but if it's needed we may add support for multiple keys.
