### ISSUE TITLE
Need node-12.x

### ISSUE THREAD

**Issue by joebowbeer** [triggermesh/knative-lambda-runtime#37]
With node-10 entering its [maintenance phase](https://github.com/nodejs/Release#release-schedule
) in a couple months and node-14 on its way, it's time for a node-12.x KLR.

Can we expect KLR to keep pace with the supported [lambda runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) for node?

**Comment by sebgoa** [comment]
you are correct

**Comment by tzununbekov** [comment]
https://github.com/triggermesh/knative-lambda-runtime/pull/81
