### ISSUE TITLE
Add Java runtime

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/knative-lambda-runtime#4]
Lambda offers java8:

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by solsson** [comment]
I'd like to do this, but with Java 11. Java 10+ has native support for docker resource limits and thus behaves a lot better in k8s.

**Comment by sebgoa** [comment]
easy enough. assigned

**Comment by joveli** [comment]
how's the java runtime going , I realy need this runtime, but I don't know how to do it. wish the runtime will come soon. thanks  @solsson

**Comment by sebgoa** [comment]
@joveli can you describe your workflow to get your Java code inside this runtime, if it existed ?

**Comment by tzununbekov** [comment]
hey @joveli, if it's still relevant, we added [java8](https://github.com/triggermesh/knative-lambda-runtime#java8) runtime! Please let us know if it works for you
