### ISSUE TITLE
Fail to install runtime via tm

### ISSUE THREAD

**Issue by hechth** [triggermesh/knative-lambda-runtime#43]
The tm executable fails to install a runtime using the command `tm deploy task -f https://raw.githubusercontent.com/triggermesh/knative-lambda-runtime/master/python-3.7/runtime.yaml` from the main documentation page.

Error: `FATA[0000] the server could not find the requested resource (post tasks.tekton.dev)`

System: Ubuntu 20.04, Go 1.14.4, tm client as exe in local bin.

**Comment by sebgoa** [comment]
Do you have Tekton installed in your kubernetes cluster ?

**Comment by hechth** [comment]
No. I assume that is the reason ;)

I guess it would be good to add this to the documentation as I don't recall reading it there.

**Comment by hechth** [comment]
Managed to install the runtime task after installing tekton in the cluster!

**Comment by sebgoa** [comment]
good, I am going to create a small issue to add this to the docs
