### ISSUE TITLE
Allow preserving directory structure

### ISSUE THREAD

**Issue by antoineco** [triggermesh/knative-lambda-runtime#55]
Opening this issue on behalf of @Mukesh9092

When the handler is inside `aws/common/src/handler.js`, it might be desirable that this directory structure is preserved in the generated image.

It might also be desirable that the entire repo structure is copied inside the final image, instead of just the handler.

**Comment by mthakur-mdsol** [comment]
@sameersbn @antoineco , Has it been addressed ?

**Comment by jmcx** [comment]
Hi @mthakur-mdsol , this has been closed as stale. I have clarified this by adding a won't fix label. 

If this issue is still relevant, please reach out to discuss it: jonathan@triggermesh.com.
