### ISSUE TITLE
Make a KLR function return a CloudEvent

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/knative-lambda-runtime#56]
Maybe using this skeleton https://github.com/triggermesh/bringyourown/tree/master/targets/go

**Comment by tzununbekov** [comment]
Events wrapper interface - https://github.com/triggermesh/aws-custom-runtime/pull/23
CloudEvents attributes parameters - https://github.com/triggermesh/aws-custom-runtime/pull/24
Readme update - https://github.com/triggermesh/aws-custom-runtime/pull/25
