### ISSUE TITLE
The Function actually run on Lambda or my Kubernetes cluster？

### ISSUE THREAD

**Issue by myrat92** [triggermesh/knative-lambda-runtime#66]
When I use KLR to run AWS Lambda function in my Kubernetes cluster installed with Knative, the function actually run on Lambda or my Knative cluster？

**Comment by tzununbekov** [comment]
@Myrat92 the function run as Knative service in your cluster, AWS Lambda service is not involved.

**Comment by myrat92** [comment]
@tzununbekov thanks!
