### ISSUE TITLE
Builds repeat some steps that could be base images

### ISSUE THREAD

**Issue by solsson** [triggermesh/knative-lambda-runtime#7]
For example the node10 build template does `apk add` and some `curl` for API_VERSION and RUNTIME_VERSION. Such things are normally in static `Dockerfile`s.

Kaniko won't cache anything (unless we configure for that) so these steps are repeated over and over again. While having all setup steps clearly visible in the build template sometimes simplifies development, we should consider moving it to a gcr.io/triggermesh/... base image. Might help the versioning as well.

Ideally the generated Dockerfile deals only with the actual handler source that's in the workspace.

**Comment by tzununbekov** [comment]
Good point. We can move out all those preparation steps from buildtemplate to the Dockerfiles for each runtime in this repository and setup cloudbuild for it. 
@sebgoa we need a priority and assignee for this issue :)

**Comment by sebgoa** [comment]
I will take care of the cloudbuild

**Comment by sebgoa** [comment]
see #11

**Comment by sebgoa** [comment]
done in https://github.com/triggermesh/knative-lambda-runtime/commit/73b5ac2731a7b74c47b641e79a22eaccbe50e2aa
