### ISSUE TITLE
Latest tag missing in python37 docker repo

### ISSUE THREAD

**Issue by ironstar94** [triggermesh/knative-lambda-runtime#75]
Tag latest in the repo gcr.io/triggermesh/knative-lambda-python37 is missing resulting in pull failures unless you target a specific tag like v1.21.1 which is the latest currently available.

**Comment by tzununbekov** [comment]
@sameersbn can you check why KLR images are missing the `latest` tag?

**Comment by sameersbn** [comment]
the issue has been resolved. the `latest` tags are now in place
