### ISSUE TITLE
Update NodeJS to LTS?

### ISSUE THREAD

**Issue by stevefan1999-personal** [triggermesh/knative-lambda-runtime#76]
I need it because I have to use `fetch` in my funtions

**Comment by tzununbekov** [comment]
Hey @stevefan1999-personal, we don't have free resources right now to handle this issue, but we'll keep it on our TODO list.

**Comment by sebgoa** [comment]
Hey @stevefan1999-personal if you can join slack https://join.slack.com/t/triggermesh-community/shared_invite/zt-1kngevosm-MY7kqn9h6bT08hWh8PeltA we could talk about your issue in a bit more details, see if we can provide this update in a timeline that makes sense for you, thanks.

**Comment by sebgoa** [comment]
And to be more specific, which version would you want exactly ?

18.13.0 LTS ?

**Comment by stevefan1999-personal** [comment]
@sebgoa I suggest the otherwise. We should add it once there are more LTS releases. Right now, being able to use 18.13.0 would be good at the moment, but not sure if for long say like few years later.

**Comment by sebgoa** [comment]
I am curious, how do you use it right now ? Do you use the Function CRD ?

**Comment by stevefan1999-personal** [comment]
@sebgoa Yep. I needed the `fetch` API ([Global objects | Node.js v18.13.0 Documentation (nodejs.org)](https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch)) to add some metadata by calling another serverless function I wrote, and \`fetch\` is dated back to 18.0.0 so I suggest the current LTS would work well

**Comment by sebgoa** [comment]
ok, so if we update the runtime to 18.13.0 that would work for you ?

and I am really curious how are you using it on kubernetes with a manifest like this https://docs.triggermesh.io/transformation/functions/nodejsfunctions/ ?

**Comment by tzununbekov** [comment]
https://github.com/triggermesh/knative-lambda-runtime/pull/81

**Comment by jmcx** [comment]
@stevefan1999-personal hi there! 

This has made it into the 1.25 release, which shipped last week. 

Are you able to take it for a test drive? 

Cheers
