### ISSUE TITLE
Add validation to dockerfile steps

### ISSUE THREAD

**Issue by solsson** [triggermesh/knative-lambda-runtime#9]
It's pretty useful when we generate `Dockerfile` as a build step that we have access to the handler source. Unlike base images we can:

 * Adapt the Dockerfile to properties we detect from /workspace
 * Add commands around the Dockerfile generation that validates assumptions

For example when troubleshooting builds I've often added `RUN ls -lR` to the dockerfile to see what the state is at that point during the `build-and-push` step. We could probably also do things like:

 * For the go runtime validate in `dockerfile` so that builds don't fail with `can't load package: package handler: no Go files in /go/src/handler`.
 * For node.js we could run `node -e` with require to check that there is a handler, or something. It's quite often that the HANDLER arg doesn't match the source.

These are just ideas. I can try to produce a PR later this week.

**Comment by tzununbekov** [comment]
Agree :+1: 
Looking forward for PRs
